kind: PersistentVolume
apiVersion: v1
metadata:
  name: ghost-vol
  namespace: ghost
  labels:
      type: local
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/ghost"